// Generated by CoffeeScript 1.3.3
var cloudq, filed, http, path, render, request, template, transform, url, view, zeke, _ref;

path = require('path');

_ref = [require('http'), require('request'), require('zeke'), require('url'), require('filed'), require(path.join(__dirname, 'template'))], http = _ref[0], request = _ref[1], zeke = _ref[2], url = _ref[3], filed = _ref[4], template = _ref[5];

cloudq = process.env.VIEW_URL || 'http://localhost:3000/api';

view = cloudq + '/queues?group=true';

module.exports = function() {
  var server;
  server = http.createServer(function(req, res) {
    var pathname;
    pathname = url.parse(req.url).pathname;
    if (req.url === '/' && req.method === 'GET') {
      return request({
        uri: view,
        json: true
      }, function(e, r, b) {
        if (e != null) {
          return res.end('DB Not Found.');
        }
        return render(b, function(err, html) {
          return res.end(html);
        });
      });
    } else {
      return filed(__dirname + ("/public" + pathname)).pipe(res);
    }
  });
  return server.listen(process.env.PORT || 4000);
};

render = function(body, cb) {
  return cb(null, zeke.render(template, {
    qResults: transform(body.rows)
  }));
};

transform = function(rows) {
  var item, queue, results, state, _i, _len, _ref1, _ref2;
  results = {};
  for (_i = 0, _len = rows.length; _i < _len; _i++) {
    item = rows[_i];
    _ref1 = item.key.split('-'), queue = _ref1[0], state = _ref1[1];
    if ((_ref2 = results[queue]) == null) {
      results[queue] = {};
    }
    results[queue][state] = item.value;
  }
  return results;
};
