// Generated by CoffeeScript 1.3.3

module.exports = function() {
  return html(function() {
    head(function() {
      title('Cloudq Status');
      link({
        rel: 'stylesheet',
        href: '/css/bootstrap.min.css'
      });
      return link({
        rel: 'stylesheet',
        href: '/css/bootstrap-responsive.min.css'
      });
    });
    return body(function() {
      div('.container', function() {
        h1({
          style: 'margin-top:50px;margin-bottom:40px;'
        }, 'Cloudq Status');
        return table('.table', function() {
          var k, v, _ref, _results;
          tr(function() {
            th('Name');
            th({
              style: 'color: red'
            }, 'Queued');
            th({
              style: 'color: orange'
            }, 'Reserved');
            return th({
              style: 'color: green'
            }, 'Completed');
          });
          _ref = this.qResults;
          _results = [];
          for (k in _ref) {
            v = _ref[k];
            _results.push(tr(function() {
              td(k);
              td({
                style: 'color: read'
              }, v.queued || '0');
              td({
                style: 'color: orange'
              }, v.reserved || '0');
              return td({
                style: 'color: green'
              }, v.completed || '0');
            }));
          }
          return _results;
        });
      });
      script({
        src: 'http://cdnjs.cloudflare.com/ajax/libs/jquery/1.7.2/jquery.min.js'
      });
      return script({
        src: '/js/bootstrap.min.js'
      });
    });
  });
};
